package by.test.dartlen.gallery.data.local.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import by.test.dartlen.gallery.data.local.greendao.Images;
import by.test.dartlen.gallery.data.local.greendao.Users;

import by.test.dartlen.gallery.data.local.greendao.ImagesDao;
import by.test.dartlen.gallery.data.local.greendao.UsersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imagesDaoConfig;
    private final DaoConfig usersDaoConfig;

    private final ImagesDao imagesDao;
    private final UsersDao usersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imagesDaoConfig = daoConfigMap.get(ImagesDao.class).clone();
        imagesDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        imagesDao = new ImagesDao(imagesDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);

        registerDao(Images.class, imagesDao);
        registerDao(Users.class, usersDao);
    }
    
    public void clear() {
        imagesDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
    }

    public ImagesDao getImagesDao() {
        return imagesDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

}
